kind: Service
apiVersion: v1
metadata:
  name: dati-semantic-frontend
  namespace: ndc-dev
  labels:
    application: dati-semantic-frontend
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    deploymentConfig: dati-semantic-frontend
  type: ClusterIP
  sessionAffinity: None